name: Pull Request Checks 

on: [push]
  #pull_request:
  #paths:
  #  '**.rs'

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          #      - name: Runs Tests  
          #    uses: ./infra/actions/docker-tests
      - name: Tests
        using: 'docker'
        image: './infra/Docker-tess'
