name: Pull Request Checks 

on: 
  pull_request:
    paths:
      '**.rs'

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Image and Run Tests
        uses: docker/build-push-action@v4
        with:
          context: .
          file: './infra/Dockerfile-test'
          push: false

  
