name: Pull Request Checks 

on: [push]
  #pull_request:
  #paths:
  #  '**.rs'

jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          #      - name: Runs Tests  
          #    uses: ./infra/actions/docker-tests
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: './infra/Dockerfile-test'
          push: false

